### PR TITLE
Allowed null filtering for JSONType fields

### LINKED ISSUE #21: JSON Type
How hard would it be to add something like [`graphql-type-json`](https://github.com/taion/graphql-type-json) to this lib?

### PR DESCRIPTION
**Pull request by erikras**
Solves last issue described here: https://github.com/arackaf/mongo-graphql-starter/issues/21#issuecomment-400631553

Fixes #21.

### CODE REVIEW

**Comment by erikras** [comment]
Heh. I wonder if I can PR your PR like this? 🤷‍♂️

The tests all pass for me locally, and the generated schema works great.

**Comment by arackaf** [comment]
Great work - thanks @erikras!

**Comment by arackaf** [comment]
@erikras Your PR is merged into the feature branch, and published to npm under a new beta version.  Once the docs are updated I'll give it a real version number, but of course that doesn't stop you from using it now if you want.

**Comment by erikras** [comment]
Awesome! Thanks a million!

**Comment by arackaf** [comment]
Done and released.  I also added in `_in` filters.

**Pull request merged**
